ci(lint): do not fail linter on `push` events (#5331)
Previous behavior:
The following error was causing an exit 1 in GitHub Actions when a pushing
to the `main` branch

```
Error: Similar commit hashes detected: previous sha is equivalent to the
current sha
```

Expeceted behavior:
Allow the linter to run succesfully even if the previous SHA has no files
changed

Solution:
Add `fetch-depth: 2` to retrieve the preceding commit